apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: bakinun/auth
      context: .
      docker:
        dockerfile: packages/auth/Dockerfile
      sync:
        manual:
          - src: 'packages/auth/src/**/*.ts'
            dest: .
